### ISSUE TITLE
Use volumes for log forwarding

### ISSUE THREAD

**Issue by mickdelaney** [sixeyed/nerd-dinner#1]
Would sharing the log files using shared volumes & then using a log forwarder, maybe in another container or on the host machine be simpler than hacking IIS & the base images from microsoft ?

**Comment by artisticcheese** [comment]
Just mapping local volume to host works perfectly for IIS logs, not sure what was the reason to go that extent for logging.
```
volumes:
        - d:\data\iislogs:c:\inetpub\logs\logfiles\host

```

**Comment by sixeyed** [comment]
Redirecting the logs to a single file and tailing that file relays the logs into Docker. So instead of looking inside the container or a host mount for log entries, you do `docker logs` - and then you have the whole log plugin framework available to you. 

More detail here: [Relay IIS log entries to read them in Docker](https://blog.sixeyed.com/relay-iis-log-entries-to-read-them-in-docker/).

**Comment by artisticcheese** [comment]
You can get rid of some issues you mentioned in your blog post (namely writing to physical log file, buffer issues etc) with switching IIS to ETW events. Details here (https://artisticcheese.wordpress.com/2017/07/20/replacing-servicemonitor-exe-with-iis-error-log-events-in-windows-iis-container/)
